## OG AOI

In [8]:
path = "sample-data/og aoi (februari 2026).xls"

In [17]:
!pip install lxml

Collecting lxml
  Downloading lxml-6.1.1-cp314-cp314-win_amd64.whl.metadata (3.6 kB)
Downloading lxml-6.1.1-cp314-cp314-win_amd64.whl (4.1 MB)
   ---------------------------------------- 0.0/4.1 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.1 MB ? eta -:--:--
   --------------- ------------------------ 1.6/4.1 MB 6.6 MB/s eta 0:00:01
   ---------------------------- ----------- 2.9/4.1 MB 6.0 MB/s eta 0:00:01
   -------------------------------------- - 3.9/4.1 MB 5.7 MB/s eta 0:00:01
   ---------------------------------------- 4.1/4.1 MB 5.5 MB/s  0:00:00
Installing collected packages: lxml
Successfully installed lxml-6.1.1

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [18]:
import pandas as pd
import gspread

df_og = pd.read_html(path)[0]
df_og.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,REKAP SALES REPORT,REKAP SALES REPORT,REKAP SALES REPORT,REKAP SALES REPORT,REKAP SALES REPORT,REKAP SALES REPORT,REKAP SALES REPORT,REKAP SALES REPORT,REKAP SALES REPORT,REKAP SALES REPORT,REKAP SALES REPORT,REKAP SALES REPORT,REKAP SALES REPORT,REKAP SALES REPORT
1,Tanggal : 2026-02-01 s/d 2026-02-28,Tanggal : 2026-02-01 s/d 2026-02-28,Tanggal : 2026-02-01 s/d 2026-02-28,Tanggal : 2026-02-01 s/d 2026-02-28,Tanggal : 2026-02-01 s/d 2026-02-28,Tanggal : 2026-02-01 s/d 2026-02-28,Tanggal : 2026-02-01 s/d 2026-02-28,Tanggal : 2026-02-01 s/d 2026-02-28,Tanggal : 2026-02-01 s/d 2026-02-28,Tanggal : 2026-02-01 s/d 2026-02-28,Tanggal : 2026-02-01 s/d 2026-02-28,Tanggal : 2026-02-01 s/d 2026-02-28,Tanggal : 2026-02-01 s/d 2026-02-28,Tanggal : 2026-02-01 s/d 2026-02-28
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
import pandas as pd
from datetime import datetime


def transform_og(path):
    df = pd.read_html(path, skiprows=5)[0]
    df.columns = [
        'Date',
        'Outlet',
        'SJ',
        'No. Cust',
        'Add Info',
        'Nett',
        'Disc',
        'Grand Total',
        'User Entry',
        'Date Entry',
        'Payment Type',
        'Payment Total',
        'Lunas',
        'Tgl Lunas'
    ]

    timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')

    df.dropna(inplace=True, how='all')
    df = df [['Date','Outlet','SJ','Nett','Payment Type','Payment Total']]
    df = df.dropna(subset=['SJ'])
    df['Timestamp'] = [timestamp for i in range(len(df))]

    id_sheet = "1ZGjn85gDAQjK4H5pTLr_Ho7T64C8sswQ5acU2X3_3cs"
    worksheet_name = "DATABASE"
    credentials_file = "credentials/wh-aoi.json"

    append_dataframe(df, id_sheet, worksheet_name, credentials_file)
    return df

SyntaxError: unmatched '}' (276096306.py, line 24)

In [29]:
transform_og(path)

11 baris berhasil ditambahkan.

,Date,Outlet,SJ,Nett,Payment Type,Payment Total
0,2026-02-09,SANDANG PANGAN BALIKPAPAN,S260200006,2262500.0,ACCOUNT RECEIVABLE,2262500.0
1,2026-02-10,KEPOMPONG T1,S260200007,402200.0,ACCOUNT RECEIVABLE,402200.0
2,2026-02-11,KEPOMPONG T1,S260200008,220000.0,ACCOUNT RECEIVABLE,220000.0
3,2026-02-13,BOGA 5,S260200009,3172975.0,ACCOUNT RECEIVABLE,3172975.0
4,2026-02-13,BOGAJAYA 7,S260200010,1699375.0,ACCOUNT RECEIVABLE,1699375.0
5,2026-02-14,BOGA 5,S260200011,177284.0,ACCOUNT RECEIVABLE,177284.0
6,2026-02-14,KEPOMPONG T1,S260200012,7815450.0,ACCOUNT RECEIVABLE,7815450.0
7,2026-02-18,KEPOMPONG T1,S260200013,3052852.0,ACCOUNT RECEIVABLE,3052852.0
8,2026-02-19,KEPOMPONG T1,S260200014,3542000.0,ACCOUNT RECEIVABLE,3542000.0
9,2026-02-24,KEPOMPONG T1,S260200015,1425000.0,ACCOUNT RECEIVABLE,1425000.0
10,2026-02-27,KEPOMPONG T1,S260200016,2331050.0,ACCOUNT RECEIVABLE,2331050.0

In [20]:
path_gs = "sample-data/gs aoi (februari 2026).xls"

In [ ]:
def append_dataframe(df, spreadsheet_id, worksheet_name, credentials_file):

    gc = gspread.service_account(filename=credentials_file)
    spreadsheet = gc.open_by_key(spreadsheet_id)
    worksheet = spreadsheet.worksheet(worksheet_name)

    if not worksheet.get_all_values():
        worksheet.append_row(df.columns.tolist())

    worksheet.append_rows(
        df.values.tolist(),
        value_input_option="USER_ENTERED"
    )

    print(f"{len(df)} baris berhasil ditambahkan.")

In [45]:
def transform_gs(path):
    df = pd.read_html(path, skiprows=5)[0]
    df.columns = [
        'Date',
        'Supplier',
        'Purchase No.',
        'No. Supplier',
        'Add Info',
        'Nett',
        'Disc',
        'Grand Total',
        'User Entry',
        'Date Entry',
        'Payment Type',
        'Settled',
        'Settled Date'
    ]

    df.dropna(inplace=True, how='all')
    df = df [['Date','Supplier','Purchase No.','No. Supplier','Add Info','Nett', 'Grand Total']]
    df = df.dropna(subset=['Purchase No.'])
    return df

transform_gs(path_gs)

,Date,Supplier,Purchase No.,No. Supplier,Add Info,Nett,Grand Total
0,2026-02-07,JAWA TIMUR,P260200006,SHOPEE 31/1,NaN,50500.0,50500.0
1,2026-02-07,JAWA TIMUR,P260200007,SHOPEE 4/2,NaN,34721.0,34721.0
2,2026-02-07,JAWA TIMUR,P260200008,SHOPEE 4/2,NaN,123132.0,123132.0
3,2026-02-07,JAWA TIMUR,P260200009,SHOPEE 6/2,NaN,173000.0,173000.0
4,2026-02-07,KALIMANTAN,P260200010,MULIA JAYA 00812026,NaN,2217500.0,2217500.0
5,2026-02-10,JAWA TIMUR,P260200011,TOKOPEDIA 6/2,belanja Bu Owen,469794.0,469794.0
6,2026-02-10,JAWA TIMUR,P260200012,TOKOPEDIA 6/2,belanja bu owen,112268.0,112268.0
7,2026-02-10,JAWA TIMUR,P260200013,TOKOPEDIA 6/2,belanja bu owen,63080.0,63080.0
8,2026-02-10,JAWA TIMUR,P260200014,TOKOPEDIA 6/2,belanja bu owen,148190.0,148190.0
9,2026-02-14,JAWA TENGAH,P260200015,shoppe 260210CNCGBEF,NaN,122350.0,122350.0
10,2026-02-18,JAWA TIMUR,P260200016,shoppe 18/2,belanja novi,2500000.0,2500000.0
11,2026-02-18,JAWA BARAT,P260200017,shoppe 18/2,NaN,1781010.0,1781010.0
12,2026-02-18,BALI,P260200018,shoppe 18/2,NaN,2999000.0,2999000.0
13,2026-02-18,JAWA BARAT,P260200019,tokopedia 15/2,NaN,129373.0,129373.0
14,2026-02-18,JAWA BARAT,P260200020,tokopedia 17/2,NaN,171599.0,171599.0
15,2026-02-18,JAWA TIMUR,P260200021,ANEKA JAYA ACC 16/2,NaN,3500000.0,3500000.0
16,2026-02-21,JAWA TIMUR,P260200022,SHOPPE 2602183PKFCW7,NaN,134866.0,134866.0
17,2026-02-21,JAWA BARAT,P260200023,SHOPPE 2602183PPPCDD,NaN,210000.0,210000.0
18,2026-02-21,JAWA BARAT,P260200024,SHOPPE 260217NA050Y9,NaN,885612.0,885612.0
19,2026-02-21,JAWA BARAT,P260200025,SHOPPE 260221PQTKHYV,NaN,899040.0,899040.0
20,2026-02-21,JAWA BARAT,P260200026,SHOPPE 260216PQTKHYV,NaN,1470500.0,1470500.0
21,2026-02-21,BALI,P260200027,260214TH57B0R9,NaN,1500000.0,1500000.0
22,2026-02-27,JAWA TIMUR,P260200028,SHOPPE 26021901SW646,NaN,2640000.0,2640000.0
23,2026-02-27,JAWA TIMUR,P260200029,SHOPPE 2602224HCRX26,NaN,376823.0,376823.0
24,2026-02-27,JAWA BARAT,P260200030,SHOPPE 2602183PD751K,NaN,367650.0,367650.0
25,2026-02-27,JAWA BARAT,P260200031,SHOPPE 2602208NDKMKD,NaN,367650.0,367650.0
26,2026-02-27,JAWA TIMUR,P260200032,SHOPPE 260221AC9G7HE,NaN,742525.0,742525.0
27,2026-02-27,JAWA TENGAH,P260200033,shoppe 27/02,NaN,79120.0,79120.0